config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :templates do
    resources :documents
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'templates#index'
end

app/models/template.rb
# frozen_string_literal: true

# Template
class Template < ApplicationRecord
  has_many :documents
  has_and_belongs_to_many :questions
  before_save :version_bump

  include SoftDeletable

  private

  def version_bump
    self.version = 1 if version.nil?
    return unless documents.count.positive?

    self.version += 1
    clone_current unless id.nil?
  end

  def clone_current
    t = Template.new(Template.find(id).attributes.except('id'))
    t.version = version - 1
    t.documents = documents
    t.questions = questions
    self.documents = []
    t.save
  end
end

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, { :class => ['form-control'] } %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, { :class => ['form-control'], :rows => 10 } %>
    <small id="passwordHelpBlock" class="form-text text-muted">
      to include a question, use the {{@:question_id}} format
    </small>
  </div>

  <h3>Questions</h3>
  <%= form.collection_check_boxes(:question_ids, Question.all, :id, :to_s) do |question| %>
    <div class="form-check">
      <%= question.check_box(class: 'form-check-input') + " (#{question.object[:id]}) #{question.object[:label]}" %>
      <%= question.label(class: 'form-check-label') { '' } %>
    </div>
  <% end %>

  <hr>
  <div class="mt-2">
    <%= form.submit 'Save', { :class => ['float-left', 'btn', 'btn-primary'] } %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path, { :class => ['float-right', 'btn', 'btn-primary'] } %>

app/views/templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Templates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th>Questions</th>
      <th>Documents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.version %></td>
        <td><%= template.questions.count %></td>
        <td><%= link_to template.documents.count, template_documents_path(template) %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Create Document', new_template_document_path(template), { :class => ['btn', 'btn-primary', 'btn-sm'] } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path, { :class => ['btn-primary', 'btn']} %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path, { :class => ['float-right', 'btn', 'btn-primary'] } %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @template.content %>
</p>

<p>
  <strong>Version:</strong>
  <%= @template.version %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>